// Data for the "issues found during training sessions" report (generated 2026-10-06 from .agents/dit-tracker.md + code reading; DIT numbers matched READ-ONLY against the Development Issue Tracking sheet).
// type: D = defect (reproduced / confirmed), O = observation / behaviour to confirm with developers, S = script or wording discrepancy
module.exports = [
  // ---------- Security / authorization ----------
  { dateDiscovered: '2026-10-04', module: 'Security Management', type: 'D', severity: 'Critical',
    description: 'A user who can only VIEW Security Management (holds View_Security but not Security_EditSecurity / Security_EditUsersAndGroups) sees greyed-out icons and disabled process checkboxes, but can still change any group\'s or user\'s authorizations by sending the same request the page sends (POST /InnoPages/Security/UpdateSecurityProcess). In testing the server answered Success and the group really gained the process (reproduced 3 of 3 runs, then reverted). Any such user could grant themselves or others any process, including Security_EditSecurity (privilege escalation; 21 CFR Part 11 access-control concern).',
    rootCause: 'SecurityController.UpdateSecurityProcess / UpdateAllSecurityProcesses / UpdateUser / UpdateGroup and SecurityService.ToggleSecurityProcess perform no permission check. They only pass HttpContext.User.Identity.Name through for the audit record. The Security_Edit* processes are checked only in GetDataForEdit / GetExistingSecuritySettings to decide what to RENDER, i.e. enforcement is UI-only.',
    action: 'Enforce authorization on the server for every write action: add [Authorize(Roles = "Security_EditSecurity")] (processes) and [Authorize(Roles = "Security_EditUsersAndGroups")] (users/groups) on the controller actions and re-check in SecurityService; add an anti-forgery token; add negative tests that post the endpoints as a view-only user. Review other write endpoints in the same plugin (UpdateUser, UpdateGroup, UpdateAllSecurityProcesses were read, not posted).',
    dit: 'None found' },
  { dateDiscovered: '2026-09-16', dateNote: 'First seen in the 2026-09-16 code review; confirmed live 2026-10-06.', module: 'Lot Management / Dynamic UI (all Dynamic UI pages)', type: 'D', severity: 'Critical',
    description: 'A user holding only LE_View_Lots (Add / Edit / Delete icons disabled, double-click opens the read-only View window, Excel Import hidden) can still add, edit and delete lots by calling the server directly. Confirmed live: posting AddRecord with oper=edit changed a lot (U3 = "srv-edit"), oper=add created a new lot, and a GET to DeleteRecord (after selecting the row) deleted a lot. The delete call answers an HTTP 500 "Runtime Error" page even though the lot is deleted, so the caller cannot tell it worked. Delete is a plain GET with no anti-forgery token. The same framework serves Label Types, Facilities, Print History and other Dynamic UI pages, so they are likely affected too. Requirement LM.150420.F.1.12 (server-side enforcement) is still unmet.',
    rootCause: 'LE_Add_Lots / LE_Chg_Lots / LE_Del_Lots / EI_Lots are checked only at page Load() (icon and menu visibility). DynamicUIController.AddRecord / DeleteRecord / SubmitExcelImport and DynamicUIService.InsertRecord / UpdateRecord / DeleteRecord / Import have no authorization check. DeleteRecord has no [HttpPost] and no anti-forgery token, and throws after deleting (500 after the delete has been committed).',
    action: 'Check the definition\'s Can* process for the current user in the controller AND the service for every write (add / edit / delete / import / excel import) and return a proper "not authorized" JSON; make DeleteRecord and SubmitExcelImport [HttpPost] with anti-forgery validation; make DeleteRecord return JSON instead of throwing; add regression tests for each process.',
    dit: 'None found' },
  { dateDiscovered: '2026-10-05', module: 'Workflow Management / View And Vote', type: 'D', severity: 'Medium',
    description: 'The rule "Comments are required for rejected workflows" (for users without WM_ViewAndVoteSkipComment) only fires when a row\'s Detail dialog is opened with Reject ticked and an empty comment. A user without the skip-comment process can tick Reject on the vote grid, sign, and the rejection completes with NO comment (job Status Completed). The requirement reads as if a blank comment is always refused for such users. Also, without WM_ViewAndVoteCheckBox every vote checkbox is silently disabled, with no message saying which process is missing.',
    rootCause: 'RejectRequiresComment (= !User.IsInRole("WM_ViewAndVoteSkipComment")) is evaluated only in the client script (JobSubmission.cshtml showRejectCommentDialog, called from the Detail dialog / beforeClose). The server-side vote submission does not re-check that a comment exists for reject votes. CanCheckBoxes / CanCheckAll simply disable the inputs.',
    action: 'Validate on the server (vote submit) that a reject vote has a comment unless the user holds WM_ViewAndVoteSkipComment, and also run the client check when Reject is ticked on the grid / when Update is clicked. Add a tooltip or message naming the missing process on disabled vote checkboxes.',
    dit: 'None found' },
  { dateDiscovered: '2026-10-06', module: 'Multi Document Printing / InnoPages host', type: 'O', severity: 'Low',
    description: 'A user without BP_MultiDocumentPrint who opens the page URL directly is redirected to /InnoPages/Host/LoginRedirect?ReturnUrl=... which shows the raw ASP.NET page "Server Error in \'/InnoPages\' Application. The resource cannot be found." (HTTP 404) instead of a "not authorized" message. The tile is simply missing from the menu. Probably the same for any InnoPage whose [Authorize(Roles=...)] fails.',
    rootCause: 'The InnoPages host redirects unauthorized requests to Host/LoginRedirect, which has no route/view in the deployed host (404) so IIS shows the default error page.',
    action: 'Provide a LoginRedirect / Unauthorized page (or route) in the InnoPages host that explains "User not authorized for this task <process>" and links back to the Web Menu.',
    dit: 'None found' },
  // ---------- Print history / printing ----------
  { dateDiscovered: '2026-10-05', module: 'Print History Inquiry (Dynamic UI)', type: 'D', severity: 'High',
    description: 'On TST703, opening Print History Inquiry and clicking Retrieve Data returns HTTP 500 "Runtime Error" from DynamicUI/GridSessionGetPage for EVERY account tested (the test user and a second fixture user), with or without filters. The user sees a spinner that never ends and the Retrieve button stays disabled; no message is shown. Prints can only be verified through the older InnoView "View Print History" report.',
    rootCause: 'Not diagnosed (no IIS / event-log or DB access). The page calls the forced-filter stored procedure SP_PrintHistoryForcedFilter and reads view v_PrintHistory (rebuilt for 7.0.3 with PrintTime formatting and a join to Activity). The 500 is most likely a database that does not have the 7.0.3 view/procedure changes, or an exception in them. It is not caused by a missing Print Entity (a user with no entity gets filter "1 = 2", i.e. no rows, not an error).',
    action: 'Read the server log for the exception; on the TST703 database run EXEC [SP_PrintHistoryForcedFilter] \'PrintHistory\',\'<user>\' and SELECT TOP 1 * FROM v_PrintHistory; re-apply the 7.0.3 DB upgrade scripts if the view/procedure are missing or old. Also make the grid show an error message instead of an endless spinner when GridSessionGetPage fails.',
    dit: 'Related: #6503 (Print History view change for 7.0.3, status Failed). Not the same defect.' },
  { dateDiscovered: '2026-10-05', dateNote: 'Approximate: found in the same Print History session as the HTTP 500; not logged separately.', module: 'Print History Inquiry (Dynamic UI) / InnoView', type: 'D', severity: 'Medium',
    description: 'Test Prints never appear in Print History (neither the Dynamic UI page nor the InnoView "View Print History" report). A tester who runs a Test Print and then looks for it in Print History finds nothing.',
    rootCause: 'The forced-filter stored procedure SP_PrintHistoryForcedFilter always filters on [PrintStatus] = \'Printed\'; Test Prints are stored with status TestPrinted. (DIT #6600 records the identical root cause.)',
    action: 'Update SP_PrintHistoryForcedFilter to include \'TestPrinted\' (as stated in DIT #6600).',
    dit: '#6600 (Ready for Publish) - same issue and same root cause' },
  { dateDiscovered: '2026-09-16', module: 'Browser Printing (MDM integration)', type: 'D', severity: 'Critical',
    description: 'An MDM item\'s approved / effective status is checked once when the item is entered in the print wizard. If the item is retired or made ineffective after item entry and before the final Print click, the label still prints with the stale master data (violates FRS MDM20150514100F1.0.2). The operator sees a normal successful print.',
    rootCause: 'The status is cached in PrintSubSession (PrintMasterItem.cs, PrintSubSession.cs, PrintOptionSelectionController.cs) for the rest of the wizard; the final Print submit never re-validates it.',
    action: 'Re-validate the MDM item\'s approved/effective state (and refuse with a message) at final Print submit, not only at item entry; add a regression test (SC-10).',
    dit: 'None found' },
  { dateDiscovered: '2026-10-05', module: 'Multi Document Printing', type: 'O', severity: 'Low',
    description: 'Each Print click raises a SECOND native "Open SentinelLauncher?" prompt (the first appears when the module opens). If the prompt is dismissed the row\'s Status column shows a red X with no tooltip or message, even though the server accepted the print request. View Master / View Compare answer "No Label Master Found" for an item whose LCN is assigned and released (label master is a separate object).',
    rootCause: 'The print token is handed to the Sentinel client through the browser protocol handler (ClientPrintMethod = Sentinel); the page only polls GetPrinterStatus and maps any non-success to a generic error icon with no reason text.',
    action: 'Show the failure reason (e.g. "Sentinel did not respond - confirm the Open SentinelLauncher prompt") in the row status tooltip; consider a clearer "No label master saved for this item/label type" explanation.',
    dit: 'None found' },
  // ---------- Label Control ----------
  { dateDiscovered: '2026-10-02', module: 'Label Control', type: 'D', severity: 'Medium',
    description: 'Export Master: the Job Detail "Download" link answers HTTP 200 with an empty body (no file type, no file name) for both a no-merge (should be .zip) and a Merge (should be .pdf) job. Clicking it downloads nothing. The PDFs are written correctly to the export share, so only the download path is broken.',
    rootCause: 'The controller action ExportMaster/DownloadFile returns EmptyResult when GetDownload fails ("Job file not found for JobID"). The service stores results in FileDataB (UploadResults jobId + .zip/.pdf) while the download reads FileData mapped to the same table, so the lookup fails; not diagnosed further (no server/DB log access).',
    action: 'Trace GetDownload for a completed job (FileData vs FileDataB), return the stored bytes with Content-Type / Content-Disposition, and return a visible error instead of an empty result when the file is missing.',
    dit: 'None found' },
  { dateDiscovered: '2026-10-02', module: 'Label Control', type: 'D', severity: 'Low-Medium',
    description: 'Load Filters restores the saved Column / Operator / Value criteria but resets the LCN Status, Attachments and Label Master dropdowns to their defaults, even though Save stores them. A user reloading a saved filter silently gets a broader result set than the one saved.',
    rootCause: 'FilterSet.load() in Innovatum.Pages.LabelControl.MVC/Scripts/innovatum/FilterSet.js assigns the saved name STRING to Knockout observables that are bound to option OBJECTS (the constructor maps strings to objects; load() does not), so Knockout resets them.',
    action: 'In FilterSet.load() map the saved RecordStatus / AttachmentFilter / LabelMasterFilter names to the matching option objects before assigning (same mapping the constructor uses); add a save/load round-trip test.',
    dit: 'None found for this symptom. Related Label Control filter DITs: #5602 (Load Filter "Update version error"), #6064 (error loading public filter).' },
  { dateDiscovered: '2026-10-02', module: 'Label Control - Mass Update Versions', type: 'O', severity: 'Low',
    description: 'The job detail "Item Version" column shows the version the record had BEFORE the update (a successful v0 -> v1 update still lists 0; a following no-op job lists 1), which can read as if the update did not happen. The grid also does not show the Version column by default and lists an item\'s version rows in random order, so versions cannot be told apart without adding the column.',
    rootCause: 'The job detail reads the version stored when the job was submitted, not the result; the grid has no default sort and the Version column is optional.',
    action: 'Show "version before -> after" (or the resulting version) in the job detail; sort version rows by item and version descending by default and include Version in the default columns.',
    dit: 'None found' },
  // ---------- Master Data Management ----------
  { dateDiscovered: '2026-08-26', dateNote: 'First seen in the MDM exploratory session (date of the session log, 2026-08-26); re-verified 2026-09-29.', module: 'Master Data Management', type: 'D', severity: 'Medium',
    description: 'On every new RobarMasterData record "Labeler Duns Number" is pre-filled with 1234567890 and immediately flagged "This dropdown value is no longer a valid selection. The schema definition may have changed." even though the value is in the dropdown list. Re-selecting it does not clear the error (only choosing a different option does) and Save is blocked until then. 100% reproducible.',
    rootCause: 'Likely a stale default-value ID in the schema field configuration that no longer matches the option\'s current underlying value, so the validation treats the default as invalid.',
    action: 'Repair the field\'s default value in the RobarMasterData schema (store the option\'s current ID/value) or remove the default; make validation compare by the stored value consistently.',
    dit: 'None found' },
  { dateDiscovered: '2026-08-25', dateNote: 'First seen in the Workflow Management / MDM sessions of 2026-08-25/26; re-verified 2026-09-29.', module: 'Master Data Management / Workflow Management', type: 'O', severity: 'Low (historic)',
    description: 'Export to Excel silently failed earlier in testing: the export request returned HTTP 503 while the completion check reported true, so the user saw no error and no file. Re-checked 2026-10-04/05: NOT reproducible any more in MDM or Workflow Management (valid .xlsx downloads).',
    rootCause: 'For Workflow Management DIT #6516 documents the cause as missing Workflow Management localization records in LocalizationResourceDef (records added in the fix). The MDM half was probably the same kind of environment/service state.',
    action: 'None needed if #6516 is published to the environment under test; keep the Export_to_Excel regression specs. Consider showing an error when the export request fails.',
    dit: '#6516 (Published In Val) - Workflow Management export empty page; #6042 (Workflow Management Export to Excel project, Published In Val)' },
  { dateDiscovered: '2026-10-04', module: 'Master Data Management (Schemas)', type: 'O', severity: 'Low-Medium',
    description: 'Renaming a schema leaves its schema-level security process (SCH_<old name>) unchanged, so Schema Security (which gates schema visibility by SCH_<name>) no longer matches the schema\'s current name. Code-read only - not yet confirmed live.',
    rootCause: 'SchemasController.Save contains the comment "//TODO: when renaming a schema, rename all it\'s security processes as well" - the rename is not implemented.',
    action: 'Implement the rename of the schema\'s SCH_ process(es) (and keep group/user grants) inside Save, or block renames; confirm live first.',
    dit: 'None found' },
  { dateDiscovered: '2026-10-04', module: 'Master Data Management (RobarMasterData seed)', type: 'D', severity: 'Low-Medium',
    description: 'Two RobarMasterData fields share the share name md_charname2: "Characteristics Name 2" and "Characteristics Name 3". Consumers that look up md_charname3 (RegAffairs, Wright ItemDocs) cannot find Characteristics Name 3, and label/GUDID mappings bound to md_charname2 get two candidate fields. The Schemas editor itself refuses duplicate share names, so this came in through the install seed.',
    rootCause: 'Copy/paste typo in Innovatum.Install/ROBARDB/MasterDataIntegrity/MasterDataLinkedSchemaFieldsIntegrity.cs (line ~396): Name 3 is generated with "md_charname2" where "md_charname3" is intended (its sibling Value/UOM fields use md_charval3 / md_charuom3).',
    action: 'Change the seed to md_charname3 and add an upgrade script that corrects existing installations (and any template bindings).',
    dit: 'None found' },
  { dateDiscovered: '2026-10-04', module: 'Master Data Management - Save Search', type: 'D', severity: 'Medium',
    description: 'Save Search with "Save As New" and a name that already exists silently OVERWRITES the existing saved search (no "name is already taken" message); the dialog just closes and the old search now holds the new criteria - quiet loss of a saved filter.',
    rootCause: 'The Save As New path does not check for an existing name (the script expects "The name is already taken. To save over an existing set, select it from the drop-down.").',
    action: 'Validate the name on Save As New and show the message (or ask for confirmation to overwrite).',
    dit: 'None for this symptom. Related Save Search DITs (same area, different defect): #6536 (MDM Overwrite - Description not saved, Published In Val), #6537 (Campaign Manager equivalent).' },
  { dateDiscovered: '2026-10-04', module: 'Master Data Management - Reset', type: 'O', severity: 'Low',
    description: 'MDM\'s Reset button does not clear the filter row (Column / Operator / Value and For Items stay as they were), unlike Label Control\'s Reset.',
    rootCause: 'Reset restores only some page state; the criteria row is not cleared.',
    action: 'Make Reset clear the criteria row and restore the default columns / page size / limit (as DIT #6535 does for the public-filter case).',
    dit: 'Related: #6535 (Master Data public filter and Reset not resetting to defaults, Published In Val)' },
  { dateDiscovered: '2026-10-04', module: 'Master Data Management - Excel Import', type: 'O', severity: 'Low-Medium',
    description: '(1) A failed job\'s "Download Spreadsheet" returns the uploaded workbook unchanged, without the per-row errors - the only place the errors appear is the on-screen Errors Only grid. (2) The Job Detail "Error Message" line shows the uploaded file name even on a fully successful job; the status reads "ValidationErrors" (no space); a missing-column failure shows an empty Errors Only grid ("No records to view") which looks like "no errors". (3) A mixed sheet (one valid row + one row with a blank required cell) imports NOTHING. (4) Overwriting an approved record by import silently creates an unapproved v1.',
    rootCause: 'The download endpoint streams the stored upload, not a results workbook; job detail binds the file name into the message field; validation is all-or-nothing per file. Not diagnosed further.',
    action: 'Generate a results workbook with an Error column; show the file name in its own field and a clear message for missing columns; confirm intended all-or-nothing behavior and the silent v1 creation with the owners.',
    dit: 'None found' },
  { dateDiscovered: '2026-10-04', module: 'Master Data Management - View History', type: 'O', severity: 'Low',
    description: 'The history grid shows the same user in two spellings (MBUser1 on field edits, mbuser1 on the approval row) while the Change User filter lists only one. Header changes (Description, Effective dates) are not in Change History; approval logs ApprovalDateTime with a date-only value and does not log Approved By.',
    rootCause: 'The user name is written with different case by different write paths; only schema fields and ApprovalDateTime are audited.',
    action: 'Normalize the user name on write; confirm the audit expectation and add header fields / Approved By to the history if required.',
    dit: 'Related (different symptom): #6553 (Master Data Change History "View Detail" links broken)' },
  { dateDiscovered: '2026-10-04', module: 'Master Data Management (Schemas)', type: 'O', severity: 'Low',
    description: 'In the Schemas editor: (1) after the "This field is required." error on an empty Schema Name, the first Submit click with a valid name sends no request (second click does); (2) a Dropdown List field with no source makes the whole schema unsaveable with the generic "Invalid fields highlighted or marked with * must be corrected." and only a small * marks the field; (3) while any field is invalid the "Add New Field" link silently does nothing.',
    rootCause: 'Client-side validation state is not cleared/re-evaluated on the first Submit; error summary does not name the invalid field; Add New Field is blocked silently while invalid.',
    action: 'Re-validate and submit in one click; name the invalid field in the error dialog; show a message when Add New Field is blocked.',
    dit: 'None found' },
  { dateDiscovered: '2026-10-04', module: 'Master Data Management (messages / scripts)', type: 'S', severity: 'Low',
    description: 'Several wording / sequence differences from the formal scripts: input-mask message "Value does not conform to pattern mask" (script: "...to the pattern mask"); a 2-item Mass Unretire is submitted with no confirmation (script expects the "effective end date will be applied to all items" prompt); the Assign GTIN overwrite warning appears when the field is chosen, not at submit; three different reason-code sets across sibling actions (Assign Labels "Data Correction / General / New Entry", End Distribution "DataLoad", Approve "General Approval / QA Approval / RA Approval / Ready for GUDID"); a required field shows "This field is required." immediately on a fresh blank record.',
    rootCause: 'Behavior or seed data differs from what the scripts describe (scripts are stale or the code changed).',
    action: 'Update the formal scripts or align the behavior; consider a single reason-code list for MDM actions.',
    dit: 'None found' },
  // ---------- Field Defs / Label Types / Template Management ----------
  { dateDiscovered: '2026-10-05', module: 'Field Definitions Management', type: 'D', severity: 'Low-Medium',
    description: 'Criteria filters pass the value to SQL LIKE unescaped: in a Contains filter the underscore is a one-character wildcard (Sharename Contains "C_" also returns F_City and F_Misc1), so literal prefix searches on share names are unreliable. Limit Results and a leftover blank criteria row are also remembered per user and later make Retrieve return truncated or empty results with no message (a blank row once crashed the tab). Field definitions can never be deleted.',
    rootCause: 'The filter value is concatenated into a LIKE pattern without escaping % and _ ; persisted per-user grid state is re-applied on load without being shown; no delete is implemented for field definitions.',
    action: 'Escape LIKE wildcards (or offer a "starts with / exact" operator); show persisted filter state and a "no results because of limit" message; confirm whether delete should exist.',
    dit: 'None found' },
  { dateDiscovered: '2026-10-04', module: 'Label Type Management', type: 'O', severity: 'Low',
    description: 'Server validation wording differs from the formal script ("File Purpose value must be blank if File Extension is .btw" etc.; Description is also required). Label Types can never be deleted (trash icon permanently disabled, DynamicUI CanDelete = "N") and every new Label Type automatically gets an LT_<name> process enabled for ALL groups and users, so a typo\'d Label Type and its security process are permanent.',
    rootCause: 'The Label Types Dynamic UI definition has CanDelete = N and a post-add hook that grants the LT_ process to everyone.',
    action: 'Update the script wording; consider allowing delete of unused Label Types and granting the new LT_ process only to the creating group.',
    dit: 'Related (different defect): #6273 (Label Type Management Excel Import exception)' },
  { dateDiscovered: '2026-10-04', module: 'Template Management', type: 'O', severity: 'Low-Medium',
    description: 'Reset does not clear "Filter by Data Source": the checkbox and chosen share names come back after Reset or reload (they persist per user until a Retrieve with the box unticked), so a stale filter silently narrows every later search. "In" / "Not In" accept only comma-separated values (semicolon = no match) without saying so. The Approved dropdown and criteria rows are simply ANDed (the script describes the filter taking precedence).',
    rootCause: 'Reset restores the criteria rows but not the data-source filter state held in the per-user session.',
    action: 'Make Reset clear the data-source filter too, or show it clearly as applied; state the comma-separated format; update the script.',
    dit: 'Related: #6439 (Template Management Reset button broken)' },
  // ---------- Security Management details ----------
  { dateDiscovered: '2026-10-04', module: 'Security Management', type: 'D', severity: 'Medium',
    description: 'Assigning a group to a user DISCARDS the user\'s own individual authorizations: a user created with "Copy Security Settings From" (391 processes) that was assigned to a group and then removed from it again came back with 0 processes authorized, not the original set. Removing a group silently strips the user of everything and the earlier set cannot be recovered from the UI.',
    rootCause: 'Joining a group replaces the user-level process rows; leaving it does not restore them (not diagnosed in code).',
    action: 'Keep the user\'s own rows when a group is assigned (or warn before discarding them) and restore/retain them when the group is removed.',
    dit: 'None found' },
  { dateDiscovered: '2026-10-04', module: 'Security Management / Login', type: 'O', severity: 'Low',
    description: 'A user whose group lacks Login_WebMenu gets "User not authorized for this task." at login with no hint which process is missing; a new group with no processes therefore creates users who cannot log in. Groups and users can never be deleted from the UI (users can only be deactivated), so typo/test groups accumulate. A group Description is required although the script only lists the blank Group error.',
    rootCause: 'The login form checks Login_WebMenu and shows the generic message; no delete function exists for groups/users.',
    action: 'Name the missing process in the message; default new groups to include Login_WebMenu; consider delete for unused groups.',
    dit: 'Related enhancement requests (not the same issue): #5553 (allow removing unused security groups), #5552 (allow removing inactive users)' },
  // ---------- Workflow Management ----------
  { dateDiscovered: '2026-10-05', module: 'Workflow Management / View And Vote', type: 'O', severity: 'High (needs decision)',
    description: 'With WFRejectHasVetoPower = N (the default and the TST703 value) a workflow can end APPROVED even though one voter rejected: two groups [user A group 1, user B group 2] - A rejects (workflow stays Open), B approves -> final status Approved. The same happens for one reject plus one approve inside a single parallel group. With a Veto step (Vote Counts As Veto) a reject closes the workflow Rejected at once. Also, a later approval group can be voted BEFORE the earlier group (group 2 voted while group 1 was still pending); the order only affects notification e-mails.',
    rootCause: 'WFViewAndVoteService.cs (~line 1331): "If the global setting WFRejectHasVetoPower is off the workflow header status will be determined by the last vote." ValMaster only says rejects can optionally have veto power and that the header status is updated "by reviewing all the workflow steps"; the mixed-vote outcome with veto off is not defined (WMPreApproveUser requirement says a rejected prior step rejects the whole workflow).',
    action: 'Decide the intended rule (last vote wins vs any reject rejects) and document it in the requirement and formal scripts; if "any reject rejects", change the header-status calculation to consider all steps; decide whether later approval groups may vote early and either enforce the order or document that it is notification-only.',
    dit: 'None found' },
  { dateDiscovered: '2026-10-06', module: 'Workflow Management / Edit Workflows', type: 'D', severity: 'Medium',
    description: 'Deleting the LAST OPEN step of a workflow (Edit Workflows > Delete User, all other steps already voted) leaves the workflow with status Open forever: nothing is votable any more and it stays in Open Only lists (about 10 orphaned test workflows were found). It can only be recovered by adding a new step (Add User at End). Also: editing a mix of voted and unvoted workflows reports "Completed" for the voted one with the message "User X has already voted or does not exist." and changes nothing for it; a step user added with Edit Workflows shows with a blank Department.',
    rootCause: 'The step-delete job does not re-evaluate the workflow header status after removing the last open step (the status is only recalculated when a vote is cast).',
    action: 'After deleting/replacing steps, recalculate the workflow header status (close it as Approved/Rejected when no open step remains) or warn that no voter will remain; make the job message distinguish "no change - already voted" from success; carry Department when adding a step.',
    dit: 'None found' },
  { dateDiscovered: '2026-10-05', module: 'Workflow Management - Preset Management', type: 'O', severity: 'Low-Medium',
    description: '"Update Step" and "Delete Step" act immediately with no confirmation (only deleting a whole preset asks), so one click loses a step; Active / Description changes are saved only by "Submit Changes" and are silently discarded when another preset is selected (no unsaved-changes warning).',
    rootCause: 'The step form posts directly; the preset header form has no dirty-state check when switching presets.',
    action: 'Add a confirmation for Delete Step (and optionally Update Step) and an "unsaved changes" prompt when switching presets.',
    dit: 'None found' },
  { dateDiscovered: '2026-10-05', module: 'Workflow Management - search grid', type: 'O', severity: 'Low-Medium',
    description: 'Choosing a Column in the Advanced Options criteria row crashed the browser tab repeatedly in automated runs (headless and headed). The last search (user / status / criteria) is persisted and re-applied on page load, and the grid defaults to ascending Workflow ID so new workflows land on the last of 80+ pages. For a workflow with several steps where some are voted, the "Last User" column is blank in the grid.',
    rootCause: 'Not diagnosed for the crash; persisted search state is re-applied by design; default sort is ascending. The blank Last User is DIT #6233.',
    action: 'Investigate the criteria widget crash; default the grid to newest-first; fix the Last User population (#6233).',
    dit: '#6233 (Workflow Management - Last User not populated for multi-step workflows) for the Last User part; none for the others' },
  { dateDiscovered: '2026-10-05', module: 'Workflow Management - item / template workflows', type: 'O', severity: 'Low',
    description: 'Approving an item or template workflow sets Approved By to the WORKFLOW ID (e.g. "20261005-0017 - 10/5/2026"), not the voting user. While the workflow is open the item shows "Item being routed in workflow - cannot be modified." and the Approve Item tooltip says "User not authorized for this task \'CM_MassApprove\'", which reads like a permission problem rather than a lock. The vote result page shows "Percent Complete 100 %" on some pages and "100%" on others.',
    rootCause: 'By design for traceability (the voter is in the workflow history); the tooltip reuses the authorization message for the locked state; two pages format the percentage differently.',
    action: 'Confirm the audit intent; use a "being routed in workflow" tooltip for the lock; format the percentage consistently.',
    dit: 'None found' },
  // ---------- Environment ----------
  { dateDiscovered: '2026-10-02', module: 'Environment / Global Settings', type: 'O', severity: 'Low',
    description: 'Turning on the LabelControl_MasterDataMustExist global setting makes Assign Control Number fail for every item without Master Data ("LCN record not created. Could not find Master Data record..."). Intended behavior, but it silently broke every Label Control test until the setting was turned off, and the message is only on the job detail.',
    rootCause: 'Configuration-driven validation.',
    action: 'None required; document the setting prominently in the Label Control test notes and show the message on the assign dialog.',
    dit: 'None found' },
  // ---------- Lot Management details ----------
  { dateDiscovered: '2026-10-06', module: 'Lot Management', type: 'D', severity: 'Medium',
    description: 'No Lots field is required on TST703: a completely blank record (blank order, lot and item number) is accepted (a second identical blank record is refused with "Record already exists", as is a duplicate order/lot/item/entity), and a lot for a NONEXISTENT item number is accepted too. The "Row N is missing a value for the X column which is specified as Required" import validation is therefore unreachable on this environment.',
    rootCause: 'The fresh-install seed (DynamicUIDetailDefaultRecords.cs) marks Lots.ItemNumber Required = Y, but the upgrade script (Robar/DB/UpgradeScripts/DynamicUI_LotManagement_Upgrade.sql) ships every Lots field Required = N, violating the "seed data must mirror the upgrade script" rule; no item-existence validation is applied on insert.',
    action: 'Make the upgrade script and the seed agree (Order/Lot/Item required) and add item-existence validation; provide an upgrade script that sets Required for existing installations.',
    dit: 'None found' },
  // ---------- Added 2026-10-08 ----------
  { dateDiscovered: '2026-10-06', module: 'Lot Management - Save Search / Load Search', type: 'O', severity: 'Low',
    description: 'Saving a search under an existing name overwrites the criteria but keeps the OLD description; Load Search restores the criteria only (not the sort or page); there is no way to delete a saved search from the UI.',
    rootCause: 'The save routine updates the criteria column only; no delete action exists in the dialog.',
    action: 'Update the description on overwrite (or prompt), and add a delete option for saved searches.',
    dit: 'None found' },
  { dateDiscovered: '2026-10-07', dateNote: 'Approximate: logged 2026-10-07 after the UAT_6356 re-execution on VAL703.', module: 'Print by Lot - Manufactured field (UAT_6356)', type: 'D', severity: 'Low-Medium',
    description: 'Executing UAT_6356 on VAL703: steps 12 and 16 do not match the document. With EditMode Enabled and the Override Lot Data box ticked, the Manufactured field is ENABLED (document expects the opposite for those steps). The Override checkbox cannot be seen in screenshots (DOM only). Changing the LocalizationResourceDef EditMode value had no effect until a ServiceHost restart AND IIS reset.',
    rootCause: 'Document text predates the BP_AllowMfgChangeAtPrint / EditMode behavior; localization resources are cached per process.',
    action: 'Correct the UAT steps (done in the executed copy) and document the restart requirement after LocalizationResourceDef changes.',
    dit: '#6356 (the UAT under execution); none for the caching behavior' },
  { dateDiscovered: '2026-10-07', module: 'Print by Lot - Printers dropdown', type: 'O', severity: 'Low-Medium',
    description: 'When Printer Control has no "*" (default) record the Printers dropdown on Print by Lot is empty with no message, so the user cannot print and gets no explanation. The legacy Print button also needs a genuine user click: without user activation the browser silently blocks the sentinel: launch and the page reports "Timeout waiting for Sentinel." / status Failed after 100 s.',
    rootCause: 'Printer list is built from Printer Control records; the sentinel: protocol launch is blocked by Chrome without a user gesture (automation artifact).',
    action: 'Show a "No printers configured" message; (the click issue is an automation artifact, not a defect).',
    dit: 'Related: #6511 (Print History Exact Reprint - "Timeout waiting for Sentinel.") - same message, different path' },
  { dateDiscovered: '2026-10-07', dateNote: 'Approximate: logged with the 2026-10-07 Print by Lot work.', module: 'Print by Lot - Test Print', type: 'O', severity: 'Low',
    description: 'Test Print on the legacy Print by Lot screen did not complete under Playwright automation although a normal print did; cause not understood.',
    rootCause: 'Not diagnosed.',
    action: 'Reproduce manually; check the Sentinel launcher log for the PRINTPRNQUEUE request.',
    dit: 'Related: #6368 (Test Print indicator to Print Server) - not the same symptom' },
  { dateDiscovered: '2026-10-07', module: 'Security Management - new user password rules', type: 'D', severity: 'Medium',
    description: 'Creating a user in Security Management does not enforce the password global settings (MinLength, NeedsLetters, NeedsNumbers); a password that breaks the rules is accepted. The new login page and the Password Change / Password Reset modules do enforce them, so the four surfaces disagree. Full matrix in Password-Settings-Matrix-2026-10-07.xlsx.',
    rootCause: 'The Security Management plugin does not call the shared password validation (confirmed in source).',
    action: 'Call the same password validator from the Security Management create / reset path.',
    dit: '#6512 (Security Management - password rules not enforced on new users)' },
  { dateDiscovered: '2026-10-07', module: 'Password settings - other inconsistencies', type: 'D', severity: 'Low-Medium',
    description: 'ChangeOnReset has no effect (dead setting); Password Change needs no login and accepts new password = current; error messages are generic; a disabled user is shown as "Locked"; the button is labelled Reset in one place and Cancel in another; the seed user never expires. A customer report that NeedsLetters / NeedsNumbers stay enforced after being disabled could not be reproduced (likely a stale per-process settings cache until restart).',
    rootCause: 'Settings are read from LegacySettings and cached per process; several screens implement their own checks.',
    action: 'Centralize validation, remove or wire the ChangeOnReset setting, and make messages and labels consistent; document the restart requirement after changing password settings.',
    dit: 'Related: #6512; none for the rest' },
  { dateDiscovered: '2026-10-07', module: 'Dictionary Management - Retire / Unretire', type: 'O', severity: 'Low-Medium',
    description: '[Re-check 2026-10-09 against ValMaster: BY DESIGN (F.8.16, F.8.7-F.8.9); no action needed.] Unretire resets the record\'s Effective Begin to the time of the unretire (original value lost); Retire works on an UNAPPROVED record; the Retire/Unretire job page first shows "Selected: 0" with all controls disabled before the real count appears.',
    rootCause: 'Unretire re-stamps Effective Begin; no approval check on retire; the page loads in two stages.',
    action: 'Confirm intent; preserve Effective Begin or document it; block or warn on retiring unapproved records.',
    dit: 'None found' },
  { dateDiscovered: '2026-10-07', module: 'Dictionary Management - Excel Import / Export', type: 'O', severity: 'Low',
    description: '[Re-check 2026-10-09 against ValMaster: the template headers (F.2.10) and no signature on Export (F.6.7) are CORRECT; the script wording was wrong.] Wording differs from the formal script: "Row already in Database" (script: "...in database"); template headers are EffectiveBegin / EffectiveEnd / ApprovalDateTime (script: "Effective Begin Date", "Effective End Date", "ApprovedDate"); the Export job has no e-signature block while the other bulk actions do.',
    rootCause: 'Scripts and UI text drifted apart.',
    action: 'Align the scripts (or the UI text); confirm Export intentionally needs no signature.',
    dit: 'None found' },
  { dateDiscovered: '2026-10-07', module: 'Dictionary Management - security', type: 'S', severity: 'Medium',
    description: 'Menu items are disabled client-side ("User not authorized for this task DM_<Process>.") and Excel Import checks the signer\'s rights on submit, but a server-side check of New Entry / New Version / mass actions with the UI bypassed was not demonstrated.',
    rootCause: 'Not demonstrated either way (the dialog URL needs its parent frame).',
    action: 'Developer check of server-side authorization, given Lot Management / DynamicUI have none.',
    dit: 'None found' },
].concat(require('./new-entries-2026-10-09.js'));
